# Set build constants to be read by mkversion.cmd

# Product name
PRODUCTNAME = Universal Audio Driver for OS/2

# Full UNIAUD build version
# BUILDVERSION must be 3 parts, and only numbers like 5.44.108
# The second and third numbers must be 2 digits
BUILDVERSION = 3.01.01

# Fixpack version
# Use this if you want to add extra chars (comments) to bldlevel
# ex RC3  GA  FIXPACK2 beta_47
# Comment out to avoid a fixpack line in bldlevel
FIXPACK = SVN
